### ISSUE TITLE
multidigit-recognition 数据

### ISSUE THREAD

**Issue by betars** [dl-lab/dnn-multidigit-recognition#1]
可否总结下关于multidigit-recognition 的公开数据集。

**Comment by Devin-Sun** [comment]
It's not an issue for implementation of this paper. The data set  could be found in http://ufldl.stanford.edu/housenumbers/

**Comment by piaobuliao** [comment]
@sundonghui  你好,看了下这篇论文,好像他没有明确给出他的深度学习模型啊,只有文字描述,"Our best architecture consists of eight convolutional hidden layers, one locally connected hidden
layer, and two densely connected hidden layers. All connections are feedforward and go from one
layer to the next (no skip connections). The first hidden layer contains maxout units (Goodfellow
et al., 2013) (with three filters per unit) while the others contain rectifier units (Jarrett et al., 2009;
Glorot et al., 2011). The number of units at each spatial location in each layer is [48, 64, 128,
160] for the first four layers and 192 for all other locally connected layers. The fully connected
layers contain 3,072 units each. Each convolutional layer includes max pooling and subtractive
normalization. The max pooling window size is 2 × 2. The stride alternates between 2 and 1 at each
layer, so that half of the layers don’t reduce the spatial size of the representation. All convolutions
use zero padding on the input to preserve representation size. The subtractive normalization operates
on 3x3 windows and preserves representation size. All convolution kernels were of size 5 × 5. We
trained with dropout applied to all hidden layers but not the input",

不是很懂啊, 请问下这篇论文的深度学习模型和Vgg这种差不多吗?
如果是的话,那它怎么处理结果是变长的,比如对于门牌号,有的是个位数,有的是三位数,而vgg这种分类的话,结果就是对应某个类别的标签就行了
